spring.application.name=consumer
server.port=8081

spring.cloud.function.definition=riderLocationConsumer;riderStatusConsumer
spring.cloud.stream.function.definition=riderLocationConsumer;riderStatusConsumer
spring.cloud.stream.bindings.riderLocationConsumer-in-0.destination=rider-location-topic
spring.cloud.stream.bindings.riderStatusConsumer-in-0.destination=rider-status-topic
spring.cloud.stream.kafka.binder.brokers=localhost:9092


#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=my-group
#
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.properties.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.value.default.type=com.kafka.consumer.RiderLocation
