spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.value.default.type: com.example.producer.model.User
  cloud:
    function:
      definition: UpperCaseFunction
    function.web.path: /uppercase
