spring:
  application:
    name: producer
  cloud:
    function:
      definition: riderLocationSupplier;riderStatusSupplier
    stream:
      bindings:
        riderLocationSupplier-out-0:
          destination: rider-location-topic
          content-type: application/json
        riderStatusSupplier-out-0:
          destination: rider-status-topic
          content-type: application/json
      poller:
        fixed-delay: 1000
        kafka:
          binder:
            brokers: localhost:9092

## Enable when using Kafka as the message broker
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
#        spring.json.value.default.type: com.example.producer.model.User
#  cloud:
#    function:
#      definition: UpperCaseFunction
#    function.web.path: /uppercase
